### ISSUE TITLE
Where should config live?

### ISSUE THREAD

**Issue by robintaylor** [DataVault/datavault#145] opened 2015-10-05 13:35 UTC
Config values currently live in the build.properties file or the Spring config files, this makes it difficult to edit at run time. Some alternatives would be...

1. Have a run time directory outwith the web and put config therein.
2. Move the config into the database.
3.?

**Comment by stuartlewis** [comment] 2015-10-05 13:52
Not sure if this is useful? http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

(Duplicate of #24 ?)

**Comment by robintaylor** [comment] 2015-10-05 14:05
Yes, this is a duplicate, my bad. The main question is, if we externalise the config into files, then where would they live? Would we then have to have some sort of run time directory? Going off at a tangent, where will logs live?

**Comment by stuartlewis** [comment] 2016-06-01 18:20
Complete

**Closed** 2016-06-01 18:21 UTC
